### ISSUE TITLE
Archival failure: invalid UTF-8 

### ISSUE THREAD

**Issue by itkovian** [itkovian/sarchive#38]
~~~~
[2020-01-07T20:44:18.820585657+01:00][sarchive][ERROR] processing failed: Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }
~~~~

**Comment by itkovian** [comment]
~~~~
➜ hexyl job.8812971_environment | bat
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ STDIN
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ ┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
   2   │ │00000000│ bc 00 00 00 5f 4d 6f 64 ┊ 75 6c 65 54 61 62 6c 65 │×000_Mod┊uleTable│
   3   │ │00000010│ 30 31 31 5f 3d 4c 32 46 ┊ 73 62 43 39 73 61 57 4a │011_=L2F┊sbC9saWJ│
   4   │ │00000020│ 6d 5a 6d 6b 76 4d 79 34 ┊ 79 4c 6a 45 74 52 30 4e │mZmkvMy4┊yLjEtR0N│
~~~~

~~~~
✗ ./utf8.py job.8812971_environment
Traceback (most recent call last):
  File "./utf8.py", line 4, in <module>
    for i in f:
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 0: invalid start byte
~~~~

**Comment by itkovian** [comment]
We need to skip the first 4 bytes.
~~~~
static int
_read_data_array_from_file(int fd, char *file_name, char ***data,
			    uint32_t * size, struct job_record *job_ptr)
{
	int pos, buf_size, amount, i, j;
	char *buffer, **array_ptr;
	uint32_t rec_cnt;

	xassert(file_name);
	xassert(data);
	xassert(size);
	*data = NULL;
	*size = 0;

	amount = read(fd, &rec_cnt, sizeof(uint32_t));
	if (amount < sizeof(uint32_t)) {
		if (amount != 0)	/* incomplete write */
			error("Error reading file %s, %m", file_name);
		else
			verbose("File %s has zero size", file_name);
		return -1;
	}

	if (rec_cnt >= INT_MAX) {
		error("%s: unreasonable record counter %d in file %s",
		      __func__, rec_cnt, file_name);
		return -1;
	}

	if (rec_cnt == 0) {
		*data = NULL;
		*size = 0;
		return 0;
	}
// <snip>
~~~~
